version: 0.2    
phases:
  install:
    runtime-versions:
        dotnet: 6
  build:
    commands:
      - dotnet restore ./VerySimpleAPI.sln
      - dotnet build ./VerySimpleAPI.sln
  post_build:
    commands:
      - dotnet publish -c Release -o ./publish
  artifacts:
    files:
      - './publish'
